# -*- coding: utf-8 -*-
"""C_Look.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ta3-ls2naeWwaFSYwe-YWEOyooX5Nv0x
"""

def clook_right_first_fixed(queue, start):
    path = [start]
    total_distance = 0
    current = start

    # Split requests into right and left
    right = sorted([r for r in queue if r >= start])
    left = sorted([r for r in queue if r < start])

    # 1. Serve right requests (ascending order)
    for req in right:
        total_distance += abs(current - req)
        current = req
        path.append(req)

    # 2. Jump to the smallest request on the left (circular movement)
    if left:
        total_distance += abs(current - left[0])  # jump cost
        current = left[0]
        path.append(current)

        # 3. Serve remaining left requests (ascending order)
        for req in left[1:]:
            total_distance += abs(current - req)
            current = req
            path.append(req)

    return total_distance, path


queue = [98, 183, 37, 122, 14, 124, 65, 67]
start = 53

distance, path = clook_right_first_fixed(queue, start)
print("Path:", path)
print("Total cylinder movement:", distance)